services:
  check-cuda:
    container_name: check-cuda
    build:
      context: .
    restart: no
    environment:
      - SHABTI_MODELS_DIR=/root/.cache/fastembed=value
      - TIKA_CLIENT_ONLY=True
      - 'TIKA_SERVER_ENDPOINT=http://tika:9998'
    volumes:
      - shabti-models:/root/.cache/fastembed
      - shabti-hf:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  ollama:
    container_name: ollama
    image: ollama/ollama:0.18.2
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  tika:
    container_name: tika
    image: apache/tika:3.3.0.0-full
    ports:
      - "9998:9998"
    restart: unless-stopped


volumes:
  ollama:
  shabti-models:
  shabti-hf: